{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "connection-manager.fullname" . }}-ingress
{{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/
            backend:
              serviceName: {{ include "connection-manager.fullname" . }}-api
              servicePort: {{ .Values.api.ports.containerPort }}
          - path: /
            backend:
              serviceName: {{ include "connection-manager.fullname" . }}-ui
              servicePort: {{ .Values.ui.ports.containerPort }}
{{- end -}}
