apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name}}-migration-job
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-migration-job"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
      - name: db-migration
          {{- with .Values.api }}
        image: "{{ .image.name }}:{{ .image.version }}"
          {{- end }}
        command:
        - /usr/local/bin/npm
        args:
        - run
        - migrate-and-seed
        env:
        - name: DATABASE_HOST
          value: {{ .Values.db.host }}
        - name: DATABASE_USER
          value: {{ .Values.db.user }}
        - name: DATABASE_PASSWORD
          value: {{ .Values.db.password }}
        - name: DATABASE_SCHEMA
          value: {{ .Values.db.schema }}
        - name: DATABASE_PORT
          value: {{ .Values.db.port | quote }}
      restartPolicy: OnFailure
  backoffLimit: 20
