{{- if and (not .Values.api.disabled) (.Values.api.rbac.enabled) -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.api.serviceAccountNameOverride }}
  name: {{ .Values.api.serviceAccountNameOverride }}
  {{- else }}
  name: {{ include "connection-manager.fullname" . }}-api
  {{- end }}
  labels:
    app.kubernetes.io/component: api
{{ include "connection-manager.labels" . | indent 4 }}

{{- end -}}
