api:
  image:
    name: ghcr.io/modusbox/connection-manager-api
    version: 1.7.11
  ports:
    containerPort: 3001
    nodePort: 31057
  oauth:
    enabled: "FALSE"
    issuer: https://localhost/oauth2/token
    key: mysecretkey
    secret: changeme
    resetPassword:
      issuer: https://localhost/scim2/Users
      user: myuser
      pass: changeme
  url: https://localhost
  env:
    # Name is mandatory- other details are optional. If name is omitted, no environment will be
    # created before the server starts.
    name:
    cn:
    c:
    l:
    o:
    ou:
    st:
  auth2fa:
    enabled: "FALSE"
  totp:
    admin:
      issuer: https://localhost/totp
      user: myuser
      password: changeme
    label: MCM
    issuer: MCM
  wso2:
    manager:
      service:
        url: https://localhost:9443/services/RemoteUserStoreManagerService.RemoteUserStoreManagerServiceHttpsSoap12Endpoint
        user: myuser
        pass: changeme
  extraTLS:
    certChain:
      enabled: 0
      stringValue: this_is_a_default
    rootCert:
      enabled: 0
      stringValue: this_is_a_default
  wso2TokenIssuer:
    cert:
      enabled: 0
      stringValue: this_is_a_default
    embeddedCertificate:
      enabled: 0
      stringValue: this_is_a_default
  vault:
    auth:
      k8s:
        enabled: true
        token: /var/run/secrets/kubernetes.io/serviceaccount/token
        role: demo
      appRole:
        enabled: false
        roleId: /vault/role-id
        roleSecretId: /vault/role-secret-id
    endpoint: http://vault:8200
    mounts:
      pki: pki
      intermediatePki: pki_int
      kv: secrets
    pkiBaseDomain: example.com
    signExpiryHours: 43800

ui:
  image:
    name: ghcr.io/modusbox/connection-manager-api
    version: 1.6.12
  ports:
    containerPort: 8080
    nodePort: 31627
  oauth:
    enabled: "FALSE"

db:
  user: mcm
  password: changeme
  host: localhost
  port: 3306
  schema: mcm

ingress:
  enabled: true
  host: localhost
  annotations: {}
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
# development friendly variables
imagePullPolicy: IfNotPresent
